version: '3.8'
services:
  server:
    container_name: havenojob-server
    build:
      context: server/
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - 5000:5000
  client:
    container_name: havenojob-client
    build:
      context: client/
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - 80:80
    depends_on:
      - server